import { defineStore } from 'pinia'
import { v4 as uuidv4 } from 'uuid'
import { useDiagramStore } from './diagram.js'
import {
    BF,
    foldf,
    probability,
    buildComponentIndex,
    buildProbMap,
    buildInterfaceMap,
    checkFaultTreeRule,
    translateCFT,
    buildSystemComponent,
    findFreeTargets,
    type RuleResult,
    type BoolFormula,
} from '../core/index.js'
import type {
    StoreNode,
    StoreGate,
    StoreSCRef,
    StoreEdge,
    StoreCFT,
    StoreComponent,
    StoreInterface,
    GateType,
} from '../core/index.js'

type CftNodeData = StoreNode & { auto?: boolean }
type CftGateData = StoreGate & { auto?: boolean }
type CftSCRefData = StoreSCRef & { auto?: boolean }
type CftEdgeData = StoreEdge & { auto?: boolean }

interface CftData {
    nodes: CftNodeData[]
    gates: CftGateData[]
    subComponents: CftSCRefData[]
    edges: CftEdgeData[]
    autoGenerated?: boolean
    seenComponentIds?: string[]
}

export const SYSTEM_CFT_KEY = '__system__'

function _buildFullStrictModel(component: StoreComponent, diagramStore: ReturnType<typeof useDiagramStore>): CftData {
    const children = diagramStore.components.filter(c => c.parentId === component.id)
    const providers = diagramStore.interfaces
        .filter(i => i.requiredComponentId === component.id)
        .map(i => diagramStore.components.find(c => c.id === i.providedComponentId))
        .filter((c): c is typeof diagramStore.components[0] => Boolean(c))
    const allDeps = [...children, ...providers]

    const CENTER_X = 300
    const OR_GATE_W = 60
    const H_SPACING = 180
    const outPortId = uuidv4()
    const eventId = uuidv4()

    if (allDeps.length === 0) {
        return {
            nodes: [
                { id: outPortId, type: 'outputPort', name: 'Out', x: CENTER_X, y: 60 },
                { id: eventId, type: 'event', name: `f(${component.name})`, x: CENTER_X, y: 200, probability: 0, isIntrinsic: true },
            ],
            gates: [],
            subComponents: [],
            edges: [
                { id: uuidv4(), sourceId: eventId, targetId: outPortId, waypoints: [] },
            ],
        }
    }

    const totalItems = allDeps.length + 1
    const totalWidth = (totalItems - 1) * H_SPACING
    const startX = CENTER_X - totalWidth / 2
    const gateId = uuidv4()

    const subComponents: CftSCRefData[] = allDeps.map((dep, i) => ({
        id: uuidv4(),
        refComponentId: dep.id,
        name: dep.name,
        x: startX + (i + 1) * H_SPACING - 70,
        y: 270,
        width: 140,
        height: 100,
    }))

    return {
        nodes: [
            { id: outPortId, type: 'outputPort', name: 'Out', x: CENTER_X, y: 60 },
            { id: eventId, type: 'event', name: `f(${component.name})`, x: startX, y: 300, probability: 0, isIntrinsic: true },
        ],
        gates: [
            { id: gateId, type: 'OR', x: CENTER_X - OR_GATE_W / 2, y: 150, width: OR_GATE_W, height: 50, inputCount: totalItems },
        ],
        subComponents,
        edges: [
            { id: uuidv4(), sourceId: eventId, targetId: gateId, targetPort: 0, waypoints: [] },
            ...subComponents.map((sc, i) => ({
                id: uuidv4(), sourceId: sc.id, targetId: gateId, targetPort: i + 1, waypoints: [],
            })),
            { id: uuidv4(), sourceId: gateId, targetId: outPortId, waypoints: [] },
        ],
        seenComponentIds: allDeps.map(d => d.id),
    }
}

function _insertOrGateForNewDeps(
    existingCft: CftData,
    newItems: Array<{ id: string; name: string }>,
    hSpacing: number,
    permanent = false,
): void {
    const tag: { auto?: true } = permanent ? {} : { auto: true }
    const outPort = existingCft.nodes.find(n => n.type === 'outputPort')
    if (!outPort) return

    const edgeToPort = existingCft.edges.find(e => e.targetId === outPort.id)
    const oldSourceId = edgeToPort?.sourceId
    if (edgeToPort) {
        existingCft.edges = existingCft.edges.filter(e => e.id !== edgeToPort.id)
    }

    const hasOld = oldSourceId !== undefined
    const inputCount = newItems.length + (hasOld ? 1 : 0)
    const gateId = uuidv4()
    const centerX = outPort.x

    const newScRefs: CftSCRefData[] = newItems.map((item, i) => ({
        id: uuidv4(),
        refComponentId: item.id,
        name: item.name,
        x: centerX - (newItems.length - 1) * hSpacing / 2 + i * hSpacing - 70,
        y: outPort.y + 210,
        width: 140,
        height: 100,
        ...tag,
    }))

    existingCft.gates.push({
        id: gateId, type: 'OR',
        x: centerX - 30, y: outPort.y + 90,
        width: 60, height: 50, inputCount,
        ...tag,
    })

    if (hasOld) {
        existingCft.edges.push({ id: uuidv4(), sourceId: oldSourceId!, targetId: gateId, targetPort: 0, waypoints: [] })
        newScRefs.forEach((sc, i) => {
            existingCft.subComponents.push(sc)
            existingCft.edges.push({ id: uuidv4(), sourceId: sc.id, targetId: gateId, targetPort: i + 1, waypoints: [], ...tag })
        })
    } else {
        newScRefs.forEach((sc, i) => {
            existingCft.subComponents.push(sc)
            existingCft.edges.push({ id: uuidv4(), sourceId: sc.id, targetId: gateId, targetPort: i, waypoints: [], ...tag })
        })
    }

    existingCft.edges.push({ id: uuidv4(), sourceId: gateId, targetId: outPort.id, waypoints: [], ...tag })
}

function _resolveInputPortProb(
    componentId: string,
    inputPortId: string,
    storeCfts: Record<string, StoreCFT>,
    probMap: Map<string, number>,
    visited: Set<string>,
): number | null {
    if (visited.has(inputPortId)) return null
    visited.add(inputPortId)

    for (const [parentId, parentCft] of Object.entries(storeCfts)) {
        if (parentId === SYSTEM_CFT_KEY) continue

        const scRef = parentCft.subComponents.find(sc => sc.refComponentId === componentId)
        if (!scRef) continue

        const compCft = storeCfts[componentId]
        if (!compCft) return null

        const inputPorts = compCft.nodes.filter(n => n.type === 'inputPort')
        const portIndex = inputPorts.findIndex(p => p.id === inputPortId)
        if (portIndex < 0) return null

        const feedingEdge = parentCft.edges.find(
            e => e.targetId === scRef.id && (e.targetPort ?? 0) === portIndex,
        )
        if (!feedingEdge) continue

        const sourceId = feedingEdge.sourceId
        const sourceNode = parentCft.nodes.find(n => n.id === sourceId)

        if (sourceNode?.type === 'event') {
            return probMap.get(sourceId) ?? 0
        }

        if (sourceNode?.type === 'inputPort') {
            return _resolveInputPortProb(parentId, sourceId, storeCfts, probMap, visited)
        }

        const gateNode = parentCft.gates?.find(g => g.id === sourceId)
        if (gateNode) {
            const inEdges = parentCft.edges.filter(e => e.targetId === sourceId)
            const inputProbs = inEdges.map(e => {
                const sNode = parentCft.nodes.find(n => n.id === e.sourceId)
                if (sNode?.type === 'event') return probMap.get(e.sourceId) ?? 0
                if (sNode?.type === 'inputPort') return _resolveInputPortProb(parentId, e.sourceId, storeCfts, probMap, visited) ?? 0
                return null
            })
            if (inputProbs.some(p => p === null)) return null
            const validProbs = inputProbs as number[]
            if (gateNode.type === 'OR') {
                return 1 - validProbs.reduce((acc, p) => acc * (1 - p), 1)
            }
            if (gateNode.type === 'AND') {
                return validProbs.reduce((acc, p) => acc * p, 1)
            }
        }
    }

    return 0
}

export const useCftStore = defineStore('cft', {
    state: () => ({
        cfts: {} as Record<string, CftData>,
        activeComponentId: null as string | null,
        selectedNodeId: null as string | null,
        selectedNodeType: null as string | null,
        connectMode: false,
        connectSourceId: null as string | null,
        connectSourcePort: 0,
        tooltip: {
            visible: false,
            x: 0,
            y: 0,
            name: '',
            probability: null as number | null,
            side: '',
        },
        parentListPopup: {
            visible: false,
            x: 0,
            y: 0,
            parents: [] as { id: string; name: string }[],
        },
    }),

    getters: {
        activeCft: (state): CftData | null => {
            if (!state.activeComponentId) return null
            return state.cfts[state.activeComponentId] ?? null
        },

        activeNodes: (state): CftNodeData[] => {
            const cft = state.activeComponentId ? state.cfts[state.activeComponentId] : null
            return cft?.nodes ?? []
        },

        activeGates: (state): CftGateData[] => {
            const cft = state.activeComponentId ? state.cfts[state.activeComponentId] : null
            return cft?.gates ?? []
        },

        activeSubComponents: (state): CftSCRefData[] => {
            const cft = state.activeComponentId ? state.cfts[state.activeComponentId] : null
            return cft?.subComponents ?? []
        },

        activeEdges: (state): CftEdgeData[] => {
            const cft = state.activeComponentId ? state.cfts[state.activeComponentId] : null
            return cft?.edges ?? []
        },

        activeEvents: (state): CftNodeData[] => {
            const cft = state.activeComponentId ? state.cfts[state.activeComponentId] : null
            return cft?.nodes.filter(n => n.type === 'event') ?? []
        },

        activeInputPorts: (state): CftNodeData[] => {
            const cft = state.activeComponentId ? state.cfts[state.activeComponentId] : null
            return cft?.nodes.filter(n => n.type === 'inputPort') ?? []
        },

        activeOutputPorts: (state): CftNodeData[] => {
            const cft = state.activeComponentId ? state.cfts[state.activeComponentId] : null
            return cft?.nodes.filter(n => n.type === 'outputPort') ?? []
        },

        inputPortProviderProbability: (state) => (inputPortId: string): number | null => {
            const diagramStore = useDiagramStore()
            const storeCfts = state.cfts as Record<string, StoreCFT>

            const interfaceMap = buildInterfaceMap(
                diagramStore.interfaces as StoreInterface[],
                storeCfts,
            )
            const conn = interfaceMap.get(inputPortId)
            if (conn) {
                return useCftStore().evaluateOutputProbability(conn.providerId)
            }

            const probMap = buildProbMap(storeCfts)

            const storeSysCft = storeCfts[SYSTEM_CFT_KEY]
            if (storeSysCft) {
                try {
                    const componentIndex = buildComponentIndex(
                        diagramStore.components as StoreComponent[],
                        storeCfts,
                        diagramStore.interfaces as StoreInterface[],
                    )
                    const systemCft = translateCFT(storeSysCft, storeCfts)
                    const resolvedOutputs = new Map<string, BoolFormula>()
                    foldf(systemCft, componentIndex, { interfaceMap, resolvedOutputs })
                    const formula = resolvedOutputs.get(inputPortId)
                    if (formula !== undefined) {
                        return probability(formula, probMap)
                    }
                } catch {}
            }

            const activeId = state.activeComponentId
            if (!activeId) return null
            return _resolveInputPortProb(activeId, inputPortId, storeCfts, probMap, new Set())
        },

        referencingComponents: (state): { id: string; name: string }[] => {
            const activeId = state.activeComponentId
            if (!activeId) return []
            const diagramStore = useDiagramStore()
            const result: { id: string; name: string }[] = []
            for (const [compId, cft] of Object.entries(state.cfts)) {
                if (compId === activeId) continue
                if (cft.subComponents.some(sc => sc.refComponentId === activeId)) {
                    if (compId === SYSTEM_CFT_KEY) {
                        result.push({ id: compId, name: 'System' })
                    } else {
                        const comp = diagramStore.components.find(c => c.id === compId)
                        if (comp) result.push({ id: comp.id, name: comp.name })
                    }
                }
            }
            return result
        },

        selectedItem: (state): CftNodeData | CftGateData | CftEdgeData | CftSCRefData | null => {
            if (!state.selectedNodeId || !state.activeComponentId) return null
            const cft = state.cfts[state.activeComponentId]
            if (!cft) return null
            switch (state.selectedNodeType) {
                case 'event':
                case 'inputPort':
                case 'outputPort':
                    return cft.nodes.find(n => n.id === state.selectedNodeId) ?? null
                case 'gate':
                    return cft.gates.find(g => g.id === state.selectedNodeId) ?? null
                case 'edge':
                    return cft.edges.find(e => e.id === state.selectedNodeId) ?? null
                case 'subComponent':
                    return cft.subComponents.find(sc => sc.id === state.selectedNodeId) ?? null
                default:
                    return null
            }
        },

        evaluateOutputProbability: (state) => (componentId: string): number | null => {
            const diagramStore = useDiagramStore()
            const storeCfts = state.cfts as Record<string, StoreCFT>
            const probMap = buildProbMap(storeCfts)
            const componentIndex = buildComponentIndex(
                diagramStore.components as StoreComponent[],
                storeCfts,
                diagramStore.interfaces as StoreInterface[],
            )
            const interfaceMap = buildInterfaceMap(
                diagramStore.interfaces as StoreInterface[],
                storeCfts,
            )

            if (componentId === SYSTEM_CFT_KEY) {
                const storeSysCft = storeCfts[SYSTEM_CFT_KEY]
                const cft = storeSysCft ? translateCFT(storeSysCft, storeCfts) : null
                if (!cft) return null
                try {
                    const formulas = foldf(cft, componentIndex, { interfaceMap })
                    const outPortId = cft.outputPorts[0]
                    if (!outPortId) return null
                    return probability(formulas.get(outPortId) ?? BF.const(false), probMap)
                } catch { return null }
            }

            const storeSysCft = storeCfts[SYSTEM_CFT_KEY]
            if (storeSysCft) {
                try {
                    const systemCft = translateCFT(storeSysCft, storeCfts)
                    const resolvedOutputs = new Map<string, BoolFormula>()
                    foldf(systemCft, componentIndex, { interfaceMap, resolvedOutputs })
                    const formula = resolvedOutputs.get(componentId)
                    if (formula !== undefined) {
                        return probability(formula, probMap)
                    }
                } catch {}
            }

            const entry = componentIndex.get(componentId)
            if (!entry) return null
            try {
                const formulas = foldf(entry.cft, componentIndex, { interfaceMap })
                const outPortId = entry.cft.outputPorts[0]
                if (!outPortId) return null
                return probability(formulas.get(outPortId) ?? BF.const(false), probMap)
            } catch { return null }
        },
    },

    actions: {
        ensureUserEditable() {
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (cft?.autoGenerated) cft.autoGenerated = false
        },

        _adoptAutoElements() {
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            cft.nodes.forEach(n => {
                delete n.auto
                if (n.type === 'outputPort' && n.name === 'Out (auto)') n.name = 'Out'
            })
            cft.gates.forEach(g => delete g.auto)
            cft.subComponents.forEach(sc => delete sc.auto)
            cft.edges.forEach(e => delete e.auto)
        },

        openCft(componentId: string) {
            if (componentId === SYSTEM_CFT_KEY) {
                const existing = this.cfts[SYSTEM_CFT_KEY]
                if (!existing || existing.autoGenerated) this.regenerateSystemCft()
                this.activeComponentId = SYSTEM_CFT_KEY
                this.deselect()
                this.connectMode = false
                this.connectSourceId = null
                this.connectSourcePort = 0
                return
            }

            let isNew = false
            if (!this.cfts[componentId]) {
                this.cfts[componentId] = { nodes: [], gates: [], subComponents: [], edges: [] }
                isNew = true
            }
            this.activeComponentId = componentId
            this.deselect()
            this.connectMode = false
            this.connectSourceId = null
            this.connectSourcePort = 0

            if (isNew) {
                const event = this.addEvent(300, 150)
                const outPort = this.addOutputPort(300, 50)
                if (event && outPort) this.addEdge(event.id, outPort.id, 0, 0)
                this.deselect()
            }
        },

        closeCft() {
            this.activeComponentId = null
            this.deselect()
            this.connectMode = false
            this.connectSourceId = null
            this.connectSourcePort = 0
        },

        removeCft(componentId: string) {
            delete this.cfts[componentId]
            if (this.activeComponentId === componentId) this.closeCft()
        },

        validateCft(componentId: string): RuleResult {
            const storeCft = this.cfts[componentId]
            if (!storeCft) return { ok: false, reason: 'No CFT found', definition: 'Def. 26' }
            const diagramStore = useDiagramStore()

            if (diagramStore.iv === null) {
                return { ok: false, reason: 'No Initial Value (IV) set — cannot evaluate maxf', definition: 'Def. 26' }
            }

            const componentIndex = buildComponentIndex(
                diagramStore.components as StoreComponent[],
                this.cfts as Record<string, StoreCFT>,
                diagramStore.interfaces as StoreInterface[],
            )
            const probMap = buildProbMap(this.cfts as Record<string, StoreCFT>)
            const interfaceMap = buildInterfaceMap(
                diagramStore.interfaces as StoreInterface[],
                this.cfts as Record<string, StoreCFT>,
            )

            const entry = componentIndex.get(componentId)
            if (!entry) return { ok: false, reason: 'Component not found in index', definition: 'Def. 26' }

            const rootIds = diagramStore.components
                .filter(c => !c.parentId && !new Set(diagramStore.interfaces.map(i => i.providedComponentId)).has(c.id))
                .map(c => c.id)
            const cfts = this.cfts as Record<string, StoreCFT>
            const storeSysCft = cfts[SYSTEM_CFT_KEY]
            const systemCft = storeSysCft ? translateCFT(storeSysCft, cfts) : null
            if (!systemCft) return { ok: false, reason: 'No system CFT available', definition: 'Def. 26' }
            const systemComponent = buildSystemComponent(
                rootIds,
                diagramStore.components as StoreComponent[],
                this.cfts as Record<string, StoreCFT>,
                diagramStore.interfaces as StoreInterface[],
                diagramStore.iv,
                systemCft,
            )

            let resolvedFormula: BoolFormula | undefined
            try {
                const resolvedOutputs = new Map<string, BoolFormula>()
                foldf(systemCft, componentIndex, { interfaceMap, resolvedOutputs })
                resolvedFormula = resolvedOutputs.get(componentId)
            } catch {}

            return checkFaultTreeRule(
                systemComponent,
                entry.component,
                entry.cft,
                componentIndex,
                probMap,
                diagramStore.iv,
                systemCft,
                interfaceMap,
                resolvedFormula,
            )
        },

        selectNode(id: string, type: string) {
            this.selectedNodeId = id
            this.selectedNodeType = type
        },

        deselect() {
            this.selectedNodeId = null
            this.selectedNodeType = null
        },

        toggleConnectMode() {
            this.connectMode = !this.connectMode
            this.connectSourceId = null
            this.connectSourcePort = 0
            if (this.connectMode) this.deselect()
        },

        setConnectSource(id: string, port = 0) {
            this.connectSourceId = id
            this.connectSourcePort = port
        },

        cancelConnect() {
            this.connectMode = false
            this.connectSourceId = null
            this.connectSourcePort = 0
        },

        showTooltip(x: number, y: number, name: string, side: string, prob: number | null = null) {
            this.tooltip = { visible: true, x, y, name, side, probability: prob }
        },

        hideTooltip() {
            this.tooltip.visible = false
        },

        moveTooltip(x: number, y: number) {
            this.tooltip.x = x
            this.tooltip.y = y
        },

        showParentListPopup(x: number, y: number, parents: { id: string; name: string }[]) {
            this.parentListPopup = { visible: true, x, y, parents }
        },

        hideParentListPopup() {
            this.parentListPopup.visible = false
        },

        addEvent(x = 300, y = 300): CftNodeData | null {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return null
            const node: CftNodeData = { id: uuidv4(), type: 'event', name: 'Event', x, y, probability: 0 }
            cft.nodes.push(node)
            this.selectNode(node.id, 'event')
            return node
        },

        addInputPort(x = 200, y = 500): CftNodeData | null {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return null
            const node: CftNodeData = { id: uuidv4(), type: 'inputPort', name: 'In', x, y, probability: 0 }
            cft.nodes.push(node)
            this.selectNode(node.id, 'inputPort')
            return node
        },

        addOutputPort(x = 200, y = 50): CftNodeData | null {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return null
            const node: CftNodeData = { id: uuidv4(), type: 'outputPort', name: 'Out', x, y }
            cft.nodes.push(node)
            this.selectNode(node.id, 'outputPort')
            return node
        },

        addGate(type: GateType = 'AND', x = 300, y = 200): CftGateData | null {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return null
            const gate: CftGateData = { id: uuidv4(), type, x, y, width: 60, height: 50, inputCount: 2 }
            cft.gates.push(gate)
            this.selectNode(gate.id, 'gate')
            return gate
        },

        addSubComponent(refComponentId: string, x = 300, y = 300): CftSCRefData | null {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return null
            if (refComponentId === this.activeComponentId) return null
            const sc: CftSCRefData = {
                id: uuidv4(), refComponentId, name: 'Sub',
                x, y, width: 140, height: 100,
            }
            cft.subComponents.push(sc)
            this.selectNode(sc.id, 'subComponent')
            return sc
        },

        addEdge(sourceId: string, targetId: string, sourcePort = 0, targetPort = 0): CftEdgeData | null {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return null
            if (sourceId === targetId) return null
            const existing = cft.edges.find(e => e.targetId === targetId && e.targetPort === targetPort)
            if (existing) return null
            if (this._wouldCreateCycle(cft, sourceId, targetId)) return null
            const edge: CftEdgeData = { id: uuidv4(), sourceId, targetId, sourcePort, targetPort, waypoints: [] }
            cft.edges.push(edge)
            const srcAuto = [...cft.nodes, ...cft.gates, ...cft.subComponents].find(el => el.id === sourceId)?.auto
            const tgtAuto = [...cft.nodes, ...cft.gates, ...cft.subComponents].find(el => el.id === targetId)?.auto
            if (srcAuto || tgtAuto) this._adoptAutoElements()
            this.selectNode(edge.id, 'edge')
            this.connectMode = false
            this.connectSourceId = null
            this.connectSourcePort = 0
            return edge
        },

        _wouldCreateCycle(cft: CftData, sourceId: string, targetId: string): boolean {
            const visited = new Set<string>()
            const stack = [targetId]
            while (stack.length > 0) {
                const current = stack.pop()!
                if (current === sourceId) return true
                if (visited.has(current)) continue
                visited.add(current)
                cft.edges.forEach(e => { if (e.sourceId === current) stack.push(e.targetId) })
            }
            return false
        },

        setIntrinsicEventProbability(componentId: string, prob: number) {
            const cft = this.cfts[componentId]
            if (!cft) return
            const node = cft.nodes.find(n => n.type === 'event' && n.isIntrinsic)
            if (node) {
                node.probability = prob
                if (cft.autoGenerated) cft.autoGenerated = false
            }
        },

        updateNode(id: string, updates: Partial<CftNodeData>) {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const idx = cft.nodes.findIndex(n => n.id === id)
            if (idx === -1) return
            const wasAuto = cft.nodes[idx].auto
            cft.nodes[idx] = { ...cft.nodes[idx], ...updates }
            if (wasAuto) this._adoptAutoElements()
        },

        updateGate(id: string, updates: Partial<CftGateData>) {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const idx = cft.gates.findIndex(g => g.id === id)
            if (idx === -1) return
            if (updates.inputCount !== undefined) {
                const gate = cft.gates[idx]
                const newCount = updates.inputCount
                if (newCount < (gate.inputCount ?? 2)) {
                    cft.edges = cft.edges.filter(e => !(e.targetId === id && (e.targetPort ?? 0) >= newCount))
                }
            }
            const wasAuto = cft.gates[idx].auto
            cft.gates[idx] = { ...cft.gates[idx], ...updates }
            if (wasAuto) this._adoptAutoElements()
        },

        updateSubComponent(id: string, updates: Partial<CftSCRefData>) {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const idx = cft.subComponents.findIndex(sc => sc.id === id)
            if (idx === -1) return
            const wasAuto = cft.subComponents[idx].auto
            cft.subComponents[idx] = { ...cft.subComponents[idx], ...updates }
            if (wasAuto) this._adoptAutoElements()
        },

        updateEdge(id: string, updates: Partial<CftEdgeData>) {
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const idx = cft.edges.findIndex(e => e.id === id)
            if (idx !== -1) cft.edges[idx] = { ...cft.edges[idx], ...updates }
        },

        removeNode(id: string) {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const node = cft.nodes.find(n => n.id === id)
            if (node?.type === 'outputPort' && cft.nodes.filter(n => n.type === 'outputPort').length <= 1) return
            const wasAuto = node?.auto
            cft.nodes = cft.nodes.filter(n => n.id !== id)
            cft.edges = cft.edges.filter(e => e.sourceId !== id && e.targetId !== id)
            if (wasAuto) this._adoptAutoElements()
            if (this.selectedNodeId === id) this.deselect()
        },

        removeGate(id: string) {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const wasAuto = cft.gates.find(g => g.id === id)?.auto
            cft.gates = cft.gates.filter(g => g.id !== id)
            cft.edges = cft.edges.filter(e => e.sourceId !== id && e.targetId !== id)
            if (wasAuto) this._adoptAutoElements()
            if (this.selectedNodeId === id) this.deselect()
        },

        removeSubComponent(id: string) {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const sc = cft.subComponents.find(s => s.id === id)
            if (sc) {
                cft.seenComponentIds = [...new Set([...(cft.seenComponentIds ?? []), sc.refComponentId])]
            }
            const wasAuto = sc?.auto
            cft.subComponents = cft.subComponents.filter(s => s.id !== id)
            cft.edges = cft.edges.filter(e => e.sourceId !== id && e.targetId !== id)
            if (wasAuto) this._adoptAutoElements()
            if (this.selectedNodeId === id) this.deselect()
        },

        removeEdge(id: string) {
            this.ensureUserEditable()
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return
            const wasAuto = cft.edges.find(e => e.id === id)?.auto
            cft.edges = cft.edges.filter(e => e.id !== id)
            if (wasAuto) this._adoptAutoElements()
            if (this.selectedNodeId === id) this.deselect()
        },

        removeSelected() {
            if (!this.selectedNodeId) return
            switch (this.selectedNodeType) {
                case 'event':
                case 'inputPort':
                case 'outputPort':
                    this.removeNode(this.selectedNodeId)
                    break
                case 'gate':
                    this.removeGate(this.selectedNodeId)
                    break
                case 'subComponent':
                    this.removeSubComponent(this.selectedNodeId)
                    break
                case 'edge':
                    this.removeEdge(this.selectedNodeId)
                    break
            }
        },

        addWaypoint(edgeId: string, index: number, x: number, y: number) {
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            const edge = cft?.edges.find(e => e.id === edgeId)
            if (!edge) return
            if (!edge.waypoints) edge.waypoints = []
            edge.waypoints.splice(index, 0, { x, y })
        },

        updateWaypoint(edgeId: string, index: number, x: number, y: number) {
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            const edge = cft?.edges.find(e => e.id === edgeId)
            if (!edge?.waypoints?.[index]) return
            edge.waypoints[index] = { x, y }
        },

        removeWaypoint(edgeId: string, index: number) {
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            const edge = cft?.edges.find(e => e.id === edgeId)
            if (!edge?.waypoints) return
            edge.waypoints.splice(index, 1)
        },

        findElement(id: string): { item: CftNodeData | CftGateData | CftSCRefData; kind: string } | null {
            const cft = this.activeComponentId ? this.cfts[this.activeComponentId] : null
            if (!cft) return null
            const node = cft.nodes.find(n => n.id === id)
            if (node) return { item: node, kind: node.type }
            const gate = cft.gates.find(g => g.id === id)
            if (gate) return { item: gate, kind: 'gate' }
            const sc = cft.subComponents.find(s => s.id === id)
            if (sc) return { item: sc, kind: 'subComponent' }
            return null
        },

        elementName(id: string): string {
            const el = this.findElement(id)
            return el?.item.name ?? '—'
        },

        getPortCount(id: string): { inputs: number; outputs: number } {
            const el = this.findElement(id)
            if (!el) return { inputs: 0, outputs: 0 }
            const { item, kind } = el
            switch (kind) {
                case 'event': return { inputs: 0, outputs: 1 }
                case 'inputPort': return { inputs: 0, outputs: 1 }
                case 'outputPort': return { inputs: 1, outputs: 0 }
                case 'gate': return { inputs: (item as CftGateData).inputCount ?? 2, outputs: 1 }
                case 'subComponent': {
                    const refCft = this.cfts[(item as CftSCRefData).refComponentId]
                    if (!refCft) return { inputs: 1, outputs: 1 }
                    return {
                        inputs: refCft.nodes.filter(n => n.type === 'inputPort').length,
                        outputs: refCft.nodes.filter(n => n.type === 'outputPort').length,
                    }
                }
                default: return { inputs: 1, outputs: 1 }
            }
        },

        getSubComponentPorts(id: string): { inputs: (CftNodeData & { index: number })[]; outputs: (CftNodeData & { index: number })[] } {
            const el = this.findElement(id)
            if (!el || el.kind !== 'subComponent') return { inputs: [], outputs: [] }
            const refCft = this.cfts[(el.item as CftSCRefData).refComponentId]
            if (!refCft) return { inputs: [], outputs: [] }
            return {
                inputs: refCft.nodes.filter(n => n.type === 'inputPort').map((n, i) => ({ ...n, index: i })),
                outputs: refCft.nodes.filter(n => n.type === 'outputPort').map((n, i) => ({ ...n, index: i })),
            }
        },

        getFreeTargetsForComponent(componentId: string): { slotId: string; label: string }[] {
            const storeCft = this.cfts[componentId]
            if (!storeCft) return []
            const coreCft = translateCFT(storeCft, this.cfts)
            const freeSlotIds = findFreeTargets(coreCft)
            return freeSlotIds.map(slotId => {
                const separatorIdx = slotId.lastIndexOf('__in_')
                const gateId = slotId.substring(0, separatorIdx)
                const inputIndex = parseInt(slotId.substring(separatorIdx + 5), 10)
                const storeGate = storeCft.gates.find(g => g.id === gateId)
                const label = storeGate
                    ? `${storeGate.type} gate (input ${inputIndex + 1} of ${storeGate.inputCount})`
                    : `Gate input ${inputIndex + 1}`
                return { slotId, label }
            })
        },

        attachChildAtPoint(
            parentId: string,
            childId: string,
            childName: string,
            attachmentPointId: string,
            x = 400, y = 300,
        ): void {
            const storeCft = this.cfts[parentId]
            if (!storeCft) return

            const separatorIdx = attachmentPointId.lastIndexOf('__in_')
            const gateId = attachmentPointId.substring(0, separatorIdx)
            const portIndex = parseInt(attachmentPointId.substring(separatorIdx + 5), 10)

            const scId = uuidv4()
            storeCft.subComponents.push({
                id: scId,
                refComponentId: childId,
                name: childName,
                x, y,
                width: 140,
                height: 100,
            })
            storeCft.edges.push({
                id: uuidv4(),
                sourceId: scId,
                targetId: gateId,
                sourcePort: 0,
                targetPort: portIndex,
                waypoints: [],
            })
            storeCft.autoGenerated = false
        },

        regenerateComponentCft(componentId: string) {
            const diagramStore = useDiagramStore()
            const component = diagramStore.components.find(c => c.id === componentId)
            if (!component) return

            const existingCft = this.cfts[componentId]
            const isUserEdited = existingCft && !existingCft.autoGenerated

            if (!isUserEdited) {
                this.cfts[componentId] = { ..._buildFullStrictModel(component, diagramStore), autoGenerated: true }
                return
            }

            const children = diagramStore.components.filter(c => c.parentId === componentId)
            const providers = diagramStore.interfaces
                .filter(i => i.requiredComponentId === componentId)
                .map(i => diagramStore.components.find(c => c.id === i.providedComponentId))
                .filter((c): c is typeof diagramStore.components[0] => Boolean(c))
            const allDeps = [...children, ...providers]

            existingCft.seenComponentIds = [...new Set([
                ...(existingCft.seenComponentIds ?? []),
                ...existingCft.subComponents.map(sc => sc.refComponentId),
            ])]
            const seenIds = new Set(existingCft.seenComponentIds)
            const newDeps = allDeps.filter(d => !seenIds.has(d.id))

            if (newDeps.length === 0) return
            _insertOrGateForNewDeps(existingCft, newDeps, 180, true)
            existingCft.seenComponentIds = [...new Set([
                ...existingCft.seenComponentIds,
                ...newDeps.map(d => d.id),
            ])]
        },

        regenerateAllStrictCfts() {
            const diagramStore = useDiagramStore()
            diagramStore.components.forEach(comp => this.regenerateComponentCft(comp.id))
        },

        regenerateSystemCft() {
            const diagramStore = useDiagramStore()
            const existing = this.cfts[SYSTEM_CFT_KEY]
            const isUserEdited = existing && !existing.autoGenerated

            if (isUserEdited) {
                const providerIds = new Set(diagramStore.interfaces.map(i => i.providedComponentId))
                const rootComps = diagramStore.components.filter(c => !c.parentId && !providerIds.has(c.id))
                existing.seenComponentIds = [...new Set([
                    ...(existing.seenComponentIds ?? []),
                    ...existing.subComponents.map(sc => sc.refComponentId),
                ])]
                const seenIds = new Set(existing.seenComponentIds)
                const newComps = rootComps.filter(c => !seenIds.has(c.id))
                if (newComps.length === 0) return
                _insertOrGateForNewDeps(existing, newComps, 200, true)
                existing.seenComponentIds = [...new Set([
                    ...existing.seenComponentIds,
                    ...newComps.map(c => c.id),
                ])]
                return
            }

            const providerIds = new Set(diagramStore.interfaces.map(i => i.providedComponentId))
            const rootComps = diagramStore.components.filter(c => !c.parentId && !providerIds.has(c.id))

            const CENTER_X = 300
            const H_SPACING = 200
            const OR_GATE_W = 60

            if (rootComps.length === 0) {
                this.cfts[SYSTEM_CFT_KEY] = {
                    nodes: [{ id: uuidv4(), type: 'outputPort', name: 'System Out', x: CENTER_X, y: 60 }],
                    gates: [],
                    subComponents: [],
                    edges: [],
                    autoGenerated: true,
                }
                return
            }

            const totalWidth = (rootComps.length - 1) * H_SPACING
            const startX = CENTER_X - totalWidth / 2
            const outPortId = uuidv4()
            const subComponents: CftSCRefData[] = rootComps.map((comp, i) => ({
                id: uuidv4(), refComponentId: comp.id, name: comp.name,
                x: startX + i * H_SPACING - 70, y: 270, width: 140, height: 100,
            }))

            const seenComponentIds = rootComps.map(c => c.id)
            if (rootComps.length === 1) {
                this.cfts[SYSTEM_CFT_KEY] = {
                    nodes: [{ id: outPortId, type: 'outputPort', name: 'System Out', x: CENTER_X, y: 60 }],
                    gates: [],
                    subComponents,
                    edges: [{ id: uuidv4(), sourceId: subComponents[0].id, targetId: outPortId, waypoints: [] }],
                    autoGenerated: true,
                    seenComponentIds,
                }
            } else {
                const gateId = uuidv4()
                this.cfts[SYSTEM_CFT_KEY] = {
                    nodes: [{ id: outPortId, type: 'outputPort', name: 'System Out', x: CENTER_X, y: 60 }],
                    gates: [{ id: gateId, type: 'OR', x: CENTER_X - OR_GATE_W / 2, y: 150, width: OR_GATE_W, height: 50, inputCount: rootComps.length }],
                    subComponents,
                    edges: [
                        ...subComponents.map((sc, i) => ({ id: uuidv4(), sourceId: sc.id, targetId: gateId, targetPort: i, waypoints: [] })),
                        { id: uuidv4(), sourceId: gateId, targetId: outPortId, waypoints: [] },
                    ],
                    autoGenerated: true,
                    seenComponentIds,
                }
            }
        },
    },
})
