import { BF, type BoolFormula } from './bool-formula.js'
import {
    createCFT,
    createGate,
    createSCRef,
    createEdge,
    createInterface,
    createComponent,
    type CFT,
    type Component,
    type ComponentIndex,
    type InterfaceMap,
} from './types.js'

export interface StoreNode {
    id: string
    type: 'event' | 'inputPort' | 'outputPort'
    name: string
    x: number
    y: number
    probability?: number
    isIntrinsic?: boolean
}

export type GateType = 'AND' | 'OR'

export interface StoreGate {
    id: string
    type: GateType
    x: number
    y: number
    width: number
    height: number
    inputCount: number
}

export interface StoreSCRef {
    id: string
    refComponentId: string
    name: string
    x: number
    y: number
    width: number
    height: number
}

export interface StoreEdge {
    id: string
    sourceId: string
    targetId: string
    sourcePort?: number
    targetPort?: number
    waypoints: { x: number; y: number }[]
}

export interface StoreCFT {
    nodes: StoreNode[]
    gates: StoreGate[]
    subComponents: StoreSCRef[]
    edges: StoreEdge[]
    autoGenerated?: boolean
}

export interface StoreComponent {
    id: string
    name: string
    x: number
    y: number
    width: number
    height: number
    parentId: string | null
}

export interface StoreInterface {
    id: string
    name: string
    requiredComponentId: string
    providedComponentId: string
    waypoints: { x: number; y: number }[]
}

export function translateCFT(storeCft: StoreCFT, storeCfts: Record<string, StoreCFT> = {}): CFT {
    const internalEvents: string[] = []
    const inputPorts: string[] = []
    const outputPorts: string[] = []

    for (const node of storeCft.nodes) {
        if (node.type === 'event') internalEvents.push(node.id)
        else if (node.type === 'inputPort') inputPorts.push(node.id)
        else if (node.type === 'outputPort') outputPorts.push(node.id)
    }

    const gateInputSlotIds = new Map<string, string[]>()
    for (const gate of storeCft.gates) {
        const slots = Array.from({ length: gate.inputCount }, (_, i) => `${gate.id}__in_${i}`)
        gateInputSlotIds.set(gate.id, slots)
    }

    const gates = storeCft.gates.map(storeGate => {
        const slots = gateInputSlotIds.get(storeGate.id)!
        let formula: BoolFormula
        if (storeGate.type === 'AND') {
            formula = slots.length > 0
                ? BF.and(...slots.map(id => BF.var(id)))
                : BF.const(true)
        } else {
            formula = slots.length > 0
                ? BF.or(...slots.map(id => BF.var(id)))
                : BF.const(false)
        }
        return createGate({
            id: storeGate.id,
            inputs: slots,
            output: storeGate.id + '.out',
            formula,
        })
    })

    const subcomponentRefs = storeCft.subComponents.map(sc => {
        const refCft = storeCfts[sc.refComponentId]
        const outputs = refCft
            ? refCft.nodes.filter(n => n.type === 'outputPort').map(n => n.id)
            : []
        const inputs = refCft
            ? refCft.nodes.filter(n => n.type === 'inputPort').map(n => n.id)
            : []
        return createSCRef({
            id: sc.id,
            componentId: sc.refComponentId,
            inputs,
            outputs,
        })
    })

    const scInputMap = new Map<string, string[]>()
    const scOutputMap = new Map<string, string[]>()
    for (const sc of subcomponentRefs) {
        scInputMap.set(sc.id, sc.inputs)
        scOutputMap.set(sc.id, sc.outputs)
    }

    const edges = storeCft.edges.map(e => {
        let source = e.sourceId
        let target = e.targetId
        const tp = e.targetPort ?? 0
        const sp = e.sourcePort ?? 0

        const gateSlots = gateInputSlotIds.get(target)
        if (gateSlots && gateSlots[tp] !== undefined) {
            target = gateSlots[tp]
        } else {
            const tInputs = scInputMap.get(target)
            if (tInputs && tInputs[tp] !== undefined) target = tInputs[tp]
        }

        return createEdge({ source, target })
    })

    return createCFT({
        internalEvents,
        inputPorts,
        outputPorts,
        gates,
        subcomponentRefs,
        edges,
    })
}

export function buildComponentIndex(
    storeComponents: StoreComponent[],
    storeCfts: Record<string, StoreCFT>,
    storeInterfaces: StoreInterface[],
): ComponentIndex {
    const index: ComponentIndex = new Map()

    for (const storeComp of storeComponents) {
        const storeCft = storeCfts[storeComp.id]
        const cft = storeCft ? translateCFT(storeCft, storeCfts) : createCFT()

        const required = storeInterfaces
            .filter(i => i.requiredComponentId === storeComp.id)
            .map(i => createInterface({ name: i.name }))
        const provided = storeInterfaces
            .filter(i => i.providedComponentId === storeComp.id)
            .map(i => createInterface({ name: i.name }))

        const component = createComponent({
            id: storeComp.id,
            name: storeComp.name,
            required,
            provided,
            faultTree: cft,
        })

        index.set(storeComp.id, { component, cft })
    }

    return index
}

export function buildProbMap(storeCfts: Record<string, StoreCFT>): Map<string, number> {
    const probMap = new Map<string, number>()
    for (const storeCft of Object.values(storeCfts)) {
        for (const node of storeCft.nodes) {
            if (node.type === 'event' && node.probability !== undefined) {
                probMap.set(node.id, node.probability)
            }
        }
    }
    return probMap
}

export function buildInterfaceMap(
    storeInterfaces: StoreInterface[],
    storeCfts: Record<string, StoreCFT>,
): InterfaceMap {
    const ifaceMap: InterfaceMap = new Map()

    const byRequirer = new Map<string, StoreInterface[]>()
    for (const iface of storeInterfaces) {
        const list = byRequirer.get(iface.requiredComponentId) ?? []
        list.push(iface)
        byRequirer.set(iface.requiredComponentId, list)
    }

    for (const [requirerId, ifaces] of byRequirer) {
        const requirerCft = storeCfts[requirerId]
        if (!requirerCft) continue
        const allInputPorts = requirerCft.nodes.filter(n => n.type === 'inputPort')

        for (const iface of ifaces) {
            const providerCft = storeCfts[iface.providedComponentId]
            const providerOutputPort = providerCft?.nodes.find(n => n.type === 'outputPort')
            if (!providerOutputPort) continue
            for (const port of allInputPorts.filter(n => n.name === iface.name)) {
                ifaceMap.set(port.id, { providerId: iface.providedComponentId, outputPortId: providerOutputPort.id })
            }
        }

        const unmappedPorts = allInputPorts.filter(n => !ifaceMap.has(n.id))
        const unmatchedIfaces = ifaces.filter(
            iface => allInputPorts.every(n => n.name !== iface.name)
                && !requirerCft.subComponents.some(sc => sc.refComponentId === iface.providedComponentId)
        )
        for (let i = 0; i < unmappedPorts.length && i < unmatchedIfaces.length; i++) {
            const iface = unmatchedIfaces[i]
            const providerCft = storeCfts[iface.providedComponentId]
            const providerOutputPort = providerCft?.nodes.find(n => n.type === 'outputPort')
            if (!providerOutputPort) continue
            ifaceMap.set(unmappedPorts[i].id, { providerId: iface.providedComponentId, outputPortId: providerOutputPort.id })
        }
    }

    return ifaceMap
}

export function findFreeTargets(cft: CFT): string[] {
    const edgeTargets = new Set(cft.edges.map(e => e.target))
    const freeTargets: string[] = []
    for (const gate of cft.gates) {
        for (const inputId of gate.inputs) {
            if (!edgeTargets.has(inputId)) freeTargets.push(inputId)
        }
    }
    return freeTargets
}

export function buildSystemCFT(
    rootComponentIds: string[],
    storeCfts: Record<string, StoreCFT>,
    providerIds: Set<string>,
): CFT {
    const participatingIds = rootComponentIds.filter(id => !providerIds.has(id))

    if (participatingIds.length === 0) {
        const outPortId = '__system_out__'
        return createCFT({ outputPorts: [outPortId] })
    }

    const outPortId = '__system_out__'
    const subcomponentRefs = participatingIds.map(id => {
        const compCft = storeCfts[id]
        const compOutPort = compCft?.nodes.find(n => n.type === 'outputPort')
        return createSCRef({
            id: `__sys_ref_${id}__`,
            componentId: id,
            inputs: [],
            outputs: compOutPort ? [compOutPort.id] : [],
        })
    })

    if (participatingIds.length === 1) {
        const ref = subcomponentRefs[0]
        const edges = ref.outputs.length > 0
            ? [createEdge({ source: ref.id, target: outPortId })]
            : []
        return createCFT({
            outputPorts: [outPortId],
            subcomponentRefs: [ref],
            edges,
        })
    }

    const orGateId = '__system_or__'
    const gateInputIds = participatingIds.map(id => `__sys_in_${id}__`)
    const formula: BoolFormula = BF.or(...gateInputIds.map(id => BF.var(id)))
    const orGate = createGate({
        id: orGateId,
        inputs: gateInputIds,
        output: orGateId + '.out',
        formula,
    })

    const edges = [
        createEdge({ source: orGateId, target: outPortId }),
        ...subcomponentRefs.map((ref, i) =>
            createEdge({ source: ref.id, target: gateInputIds[i] })
        ),
    ]

    return createCFT({
        outputPorts: [outPortId],
        gates: [orGate],
        subcomponentRefs,
        edges,
    })
}

export function buildSystemComponent(
    rootComponentIds: string[],
    storeComponents: StoreComponent[],
    storeCfts: Record<string, StoreCFT>,
    storeInterfaces: StoreInterface[],
    iv: number,
    prebuiltSystemCft?: CFT,
): Component {
    const providerIds = new Set(storeInterfaces.map(i => i.providedComponentId))
    const systemCft = prebuiltSystemCft ?? buildSystemCFT(rootComponentIds, storeCfts, providerIds)

    const subcomponents: Component[] = rootComponentIds.map(id => {
        const storeComp = storeComponents.find(c => c.id === id)!
        const cft = storeCfts[id] ? translateCFT(storeCfts[id], storeCfts) : createCFT()
        const required = storeInterfaces
            .filter(i => i.requiredComponentId === id)
            .map(i => createInterface({ name: i.name }))
        const provided = storeInterfaces
            .filter(i => i.providedComponentId === id)
            .map(i => createInterface({ name: i.name }))
        return createComponent({
            id,
            name: storeComp?.name ?? id,
            faultTree: cft,
            required,
            provided,
        })
    })

    return createComponent({
        id: '__system__',
        name: 'System',
        subcomponents,
        faultTree: systemCft,
    })
}
